"""Browse the template gallery — and scaffold the content JSON for a fill.

The gallery holds one template file plus a manifest.json per entry, in three
namespaces:

    registry/_builtin/<name>/          # generic, brand-parameterized templates that
                                       # ship with the suite (generated by the
                                       # pptx/docx library builders)
    registry/_families/<family>/       # the governed canonical per document family
    registry/<client>/<doc_type>/      # per-client instances (the exception)

This tool lets an agent (however small) discover what exists, see exactly which
fields a template needs, and emit a ready-to-edit content.json — so the next
document is a fill, not a rebuild.

Usage:
    python scripts/registry.py list                        # everything, grouped
    python scripts/registry.py list --client acme          # one client's templates
    python scripts/registry.py find --builtin exec-update
    python scripts/registry.py show --builtin exec-update  # + fields
    python scripts/registry.py show --family lessons-learned
    python scripts/registry.py show --client acme --doc-type quarterly-review
    python scripts/registry.py scaffold --builtin exec-update --out content.json
    python scripts/registry.py scaffold --builtin exec-update --out content.json --with-examples

`scaffold` writes every field key (in manifest order) with an empty value — or the
manifest's example values with --with-examples — plus one example item per row
group. Edit the values, then fill.py -> validate.py -> render. NOTE: example values
overlap the manifest's source_terms on purpose: shipping an unedited example fill
FAILS validate.py's source-residue check.
"""
from __future__ import annotations

import argparse
import json
import sys

import common as C

# Windows consoles default to cp1252 — examples legitimately contain ▲/·/—.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

GROUP_LABELS = {"_builtin": "Built-in templates (generic, fill-ready)",
                "_families": "Families (governed canonicals)"}


def _resolve_selector(args) -> tuple[str, str]:
    """Map --builtin/--family/--client+--doc-type onto (client_id, doc_type_id)."""
    picked = [bool(getattr(args, "builtin", None)), bool(getattr(args, "family", None)),
              bool(args.client and args.doc_type)]
    if sum(picked) != 1:
        sys.exit("Pick exactly one of: --builtin <name> | --family <name> | --client <c> --doc-type <t>")
    if getattr(args, "builtin", None):
        return "_builtin", args.builtin
    if getattr(args, "family", None):
        return "_families", args.family
    return args.client, args.doc_type


def _fill_hint(manifest: dict) -> str:
    client, doc_type = manifest["client"], manifest["doc_type"]
    if client == "_builtin":
        sel = f"--client _builtin --doc-type {doc_type}"
    elif client == "_families":
        sel = f"--client _families --doc-type {doc_type}"
    else:
        sel = f"--client {client} --doc-type {doc_type}"
    return (f"python scripts/fill.py {sel} --data content.json --out out.{manifest['format']}")


def _iter_manifests():
    if not C.REGISTRY.exists():
        return
    for man in sorted(C.REGISTRY.glob("*/*/manifest.json")):
        try:
            yield man, C.load_manifest(man)
        except (json.JSONDecodeError, OSError):
            continue


def cmd_list(args):
    def norm(c):
        return c if c in ("_builtin", "_families") else C.slugify(c)
    entries = [(m, d) for m, d in _iter_manifests()
               if not args.client or d.get("client") == norm(args.client)]
    if not entries:
        print("No templates registered yet." if not args.client
              else f"No templates for client '{args.client}'.")
        return
    # Builtins first, then families, then clients alphabetically.
    order = {"_builtin": 0, "_families": 1}
    entries.sort(key=lambda e: (order.get(e[1]["client"], 2), e[1]["client"], e[1]["doc_type"]))
    current = None
    for _man, d in entries:
        if d["client"] != current:
            current = d["client"]
            print(f"\n{GROUP_LABELS.get(current, current)}")
        desc = d.get("description", "")
        line = (f"  - {d['doc_type']:20}  {d['format']:5}  {len(d['fields']):3} fields  "
                f"v{d.get('version', '?')}")
        print(line + (f"  — {desc}" if desc else ""))
    print("\nDetails:   python scripts/registry.py show --builtin <name>   (or --family/--client)")
    print("Scaffold:  python scripts/registry.py scaffold --builtin <name> --out content.json")


def cmd_find(args):
    client, doc_type = _resolve_selector(args)
    try:
        tpl, manifest = C.find_template(client, doc_type)
    except FileNotFoundError as e:
        sys.exit(str(e))
    print(json.dumps({"template": str(tpl), "manifest_id": manifest["template_id"],
                      "format": manifest["format"],
                      "fields": [f["name"] for f in manifest["fields"]]}, indent=2))


def cmd_show(args):
    client, doc_type = _resolve_selector(args)
    try:
        tpl, manifest = C.find_template(client, doc_type)
    except FileNotFoundError as e:
        sys.exit(str(e))
    print(f"{manifest['template_id']}  ({manifest['format']}, v{manifest.get('version', '?')})")
    if manifest.get("description"):
        print(f"  about    : {manifest['description']}")
    print(f"  template : {tpl}")
    print(f"  source   : {manifest.get('source_file', '—')}")
    print(f"  owner    : {manifest.get('owner', '—')}   created: {manifest.get('created', '—')}")
    row_group_cols = {c for g in manifest.get("row_groups", []) for c in g["columns"]}
    print(f"  fields   ({len(manifest['fields'])}):")
    for f in manifest["fields"]:
        if f["name"] in row_group_cols:
            continue                       # shown under their row group below
        req = "" if f.get("required", True) else " (optional)"
        ex = f" e.g. {f['example'][:48]!r}" if f.get("example") else ""
        print(f"    - {f['name']:26} {f.get('type', 'text'):6}{req}{ex}")
    for g in manifest.get("row_groups", []):
        print(f"  row group '{g['name']}' (a LIST of objects; one table row per item):")
        for col in g["columns"]:
            f = next((x for x in manifest["fields"] if x["name"] == col), {})
            ex = f" e.g. {f.get('example', '')[:40]!r}" if f.get("example") else ""
            print(f"    - {col:26}{ex}")
    print("\n  Scaffold the content file, edit the values, then fill:")
    print(f"    python scripts/registry.py scaffold --client {manifest['client']} "
          f"--doc-type {manifest['doc_type']} --out content.json")
    print(f"    {_fill_hint(manifest)}")


def cmd_scaffold(args):
    client, doc_type = _resolve_selector(args)
    try:
        _tpl, manifest = C.find_template(client, doc_type)
    except FileNotFoundError as e:
        sys.exit(str(e))

    row_group_cols = {c for g in manifest.get("row_groups", []) for c in g["columns"]}
    content: dict = {}
    for f in manifest["fields"]:
        name = f["name"]
        if name in row_group_cols:
            continue
        ftype = f.get("type", "text")
        if args.with_examples and f.get("example"):
            content[name] = [f["example"]] if ftype == "list" else f["example"]
        else:
            content[name] = [] if ftype == "list" else ""
    for g in manifest.get("row_groups", []):
        item = {}
        for col in g["columns"]:
            f = next((x for x in manifest["fields"] if x["name"] == col), {})
            item[col] = f.get("example", "") if args.with_examples else ""
        content[g["name"]] = [item]
    for g in manifest.get("slide_groups", []):
        item = {}
        for f in g["fields"]:
            ftype = f.get("type", "text")
            if args.with_examples and f.get("example"):
                item[f["name"]] = [f["example"]] if ftype == "list" else f["example"]
            else:
                item[f["name"]] = [] if ftype == "list" else ""
        content[g["name"]] = [item]

    out = args.out
    from pathlib import Path
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(json.dumps(content, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Scaffold written: {out}  ({len(content)} keys)")
    print("\nFill guidance (field -> how to fill):")
    for f in manifest["fields"]:
        if f["name"] in row_group_cols:
            continue
        kind = f.get("type", "text")
        req = "" if f.get("required", True) else "  [optional]"
        print(f"  {f['name']:26} {kind:6}{req}  {f.get('guidance', '')}")
    for g in manifest.get("row_groups", []):
        print(f"  {g['name']:26} rows    one object per table row; keys: {', '.join(g['columns'])}")
    for g in manifest.get("slide_groups", []):
        mn, mx = g.get("min", 1), g.get("max")
        span = f"{mn}–{mx}" if mx else f"{mn}+"
        print(f"  {g['name']:26} slides  one object per SLIDE ({span} slides; 0 = slide removed "
              f"if optional). {g.get('purpose', '')}")
        for f in g["fields"]:
            req = "" if f.get("required", True) else "  [optional]"
            print(f"      .{f['name']:22} {f.get('type', 'text'):6}{req}  {f.get('guidance', '')}")
    if manifest.get("slides"):
        groups_by_name = {g["name"]: g for g in manifest.get("slide_groups", [])}
        print("\nSlide guide (what each slide is for):")
        for s in manifest["slides"]:
            mark = ""
            if s.get("group"):
                g = groups_by_name.get(s["group"], {})
                mn, mx = g.get("min", 1), g.get("max")
                mark = (f"  [optional — omit '{s['group']}' to drop]" if mn == 0
                        else f"  [repeatable ×{mn}–{mx or '∞'} via '{s['group']}']")
            print(f"  {s['index'] + 1:>2}. {s.get('name', ''):20} {s.get('purpose', '')}{mark}")
    if args.with_examples:
        print("\nNOTE: example values must be EDITED — an unedited example fill fails the "
              "source-residue check in validate.py (by design).")
    print(f"\nNext: {_fill_hint(manifest)}")


def _add_selectors(p, *, need_out=False):
    p.add_argument("--builtin", help="Built-in template name (registry/_builtin/<name>)")
    p.add_argument("--family", help="Family name (registry/_families/<family>)")
    p.add_argument("--client", default=None)
    p.add_argument("--doc-type", default=None)
    if need_out:
        p.add_argument("--out", required=True, help="Where to write the content JSON")
        p.add_argument("--with-examples", action="store_true",
                       help="Prefill values with the manifest's examples (must be edited)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("list", help="Everything in the gallery, grouped")
    p.add_argument("--client", default=None)
    p.set_defaults(func=cmd_list)

    for name, fn in (("find", cmd_find), ("show", cmd_show)):
        s = sub.add_parser(name)
        _add_selectors(s)
        s.set_defaults(func=fn)

    s = sub.add_parser("scaffold", help="Emit a ready-to-edit content.json for a template")
    _add_selectors(s, need_out=True)
    s.set_defaults(func=cmd_scaffold)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
